# THIS FILE IS AUTOMATICALLY GENERATED. DO NOT EDIT.
# BASED ON c:\Users\Peter\Documents\GITHUB\neptunium-master

function(add_st_target_properties TARGET_NAME)

target_compile_definitions(
    ${TARGET_NAME} PRIVATE
    "$<$<AND:$<CONFIG:Debug>,$<COMPILE_LANGUAGE:ASM>>:DEBUG>"
    "$<$<AND:$<CONFIG:Debug>,$<COMPILE_LANGUAGE:C>>:DEBUG>"
    "$<$<AND:$<CONFIG:Debug>,$<COMPILE_LANGUAGE:C>>:USE_HAL_DRIVER>"
    "$<$<AND:$<CONFIG:Debug>,$<COMPILE_LANGUAGE:C>>:STM32F302xB>"
    "$<$<AND:$<CONFIG:Debug>,$<COMPILE_LANGUAGE:C>>:STM32F302xC>"
    "$<$<AND:$<CONFIG:Debug>,$<COMPILE_LANGUAGE:CXX>>:DEBUG>"
    "$<$<AND:$<CONFIG:Debug>,$<COMPILE_LANGUAGE:CXX>>:USE_HAL_DRIVER>"
    "$<$<AND:$<CONFIG:Debug>,$<COMPILE_LANGUAGE:CXX>>:STM32F302xB>"
    "$<$<AND:$<NOT:$<CONFIG:Debug>>,$<COMPILE_LANGUAGE:C>>:USE_HAL_DRIVER>"
    "$<$<AND:$<NOT:$<CONFIG:Debug>>,$<COMPILE_LANGUAGE:C>>:STM32F302xB>"
    "$<$<AND:$<NOT:$<CONFIG:Debug>>,$<COMPILE_LANGUAGE:C>>:STM32F302xC>"
    "$<$<AND:$<NOT:$<CONFIG:Debug>>,$<COMPILE_LANGUAGE:CXX>>:USE_HAL_DRIVER>"
    "$<$<AND:$<NOT:$<CONFIG:Debug>>,$<COMPILE_LANGUAGE:CXX>>:STM32F302xB>"
)

target_include_directories(
    ${TARGET_NAME} PRIVATE
    "$<$<AND:$<CONFIG:Debug>,$<COMPILE_LANGUAGE:C>>:${PROJECT_SOURCE_DIR}/Core\\Inc>"
    "$<$<AND:$<CONFIG:Debug>,$<COMPILE_LANGUAGE:C>>:${PROJECT_SOURCE_DIR}/Drivers\\STM32F3xx_HAL_Driver\\Inc\\Legacy>"
    "$<$<AND:$<CONFIG:Debug>,$<COMPILE_LANGUAGE:C>>:${PROJECT_SOURCE_DIR}/Drivers\\STM32F3xx_HAL_Driver\\Inc>"
    "$<$<AND:$<CONFIG:Debug>,$<COMPILE_LANGUAGE:C>>:${PROJECT_SOURCE_DIR}/Drivers\\CMSIS\\Device\\ST\\STM32F3xx\\Include>"
    "$<$<AND:$<CONFIG:Debug>,$<COMPILE_LANGUAGE:C>>:${PROJECT_SOURCE_DIR}/Drivers\\CMSIS\\Include>"
    "$<$<AND:$<CONFIG:Debug>,$<COMPILE_LANGUAGE:C>>:${PROJECT_SOURCE_DIR}/Drivers\\lsm6dsox-pid>"
    "$<$<AND:$<CONFIG:Debug>,$<COMPILE_LANGUAGE:C>>:${PROJECT_SOURCE_DIR}/Drivers\\lps22hb-pid>"
    "$<$<AND:$<CONFIG:Debug>,$<COMPILE_LANGUAGE:C>>:${PROJECT_SOURCE_DIR}/Drivers\\ubx_parser>"
    "$<$<AND:$<CONFIG:Debug>,$<COMPILE_LANGUAGE:C>>:${PROJECT_SOURCE_DIR}/Drivers\\sx126x_driver\\src>"
    "$<$<AND:$<CONFIG:Debug>,$<COMPILE_LANGUAGE:C>>:${PROJECT_SOURCE_DIR}/USB_DEVICE\\App>"
    "$<$<AND:$<CONFIG:Debug>,$<COMPILE_LANGUAGE:C>>:${PROJECT_SOURCE_DIR}/USB_DEVICE\\Target>"
    "$<$<AND:$<CONFIG:Debug>,$<COMPILE_LANGUAGE:C>>:${PROJECT_SOURCE_DIR}/Middlewares\\ST\\STM32_USB_Device_Library\\Core\\Inc>"
    "$<$<AND:$<CONFIG:Debug>,$<COMPILE_LANGUAGE:C>>:${PROJECT_SOURCE_DIR}/Middlewares\\ST\\STM32_USB_Device_Library\\Class\\CDC\\Inc>"
    "$<$<AND:$<CONFIG:Debug>,$<COMPILE_LANGUAGE:C>>:${PROJECT_SOURCE_DIR}/Drivers\\tinyusb\\src>"
    "$<$<AND:$<CONFIG:Debug>,$<COMPILE_LANGUAGE:C>>:${PROJECT_SOURCE_DIR}/FATFS\\Target>"
    "$<$<AND:$<CONFIG:Debug>,$<COMPILE_LANGUAGE:C>>:${PROJECT_SOURCE_DIR}/FATFS\\App>"
    "$<$<AND:$<CONFIG:Debug>,$<COMPILE_LANGUAGE:C>>:${PROJECT_SOURCE_DIR}/Middlewares\\Third_Party\\FatFs\\src>"
    "$<$<AND:$<CONFIG:Debug>,$<COMPILE_LANGUAGE:CXX>>:${PROJECT_SOURCE_DIR}/Core\\Inc>"
    "$<$<AND:$<CONFIG:Debug>,$<COMPILE_LANGUAGE:CXX>>:${PROJECT_SOURCE_DIR}/Drivers\\STM32F3xx_HAL_Driver\\Inc\\Legacy>"
    "$<$<AND:$<CONFIG:Debug>,$<COMPILE_LANGUAGE:CXX>>:${PROJECT_SOURCE_DIR}/Drivers\\STM32F3xx_HAL_Driver\\Inc>"
    "$<$<AND:$<CONFIG:Debug>,$<COMPILE_LANGUAGE:CXX>>:${PROJECT_SOURCE_DIR}/Drivers\\CMSIS\\Device\\ST\\STM32F3xx\\Include>"
    "$<$<AND:$<CONFIG:Debug>,$<COMPILE_LANGUAGE:CXX>>:${PROJECT_SOURCE_DIR}/Drivers\\CMSIS\\Include>"
    "$<$<AND:$<CONFIG:Debug>,$<COMPILE_LANGUAGE:CXX>>:${PROJECT_SOURCE_DIR}/USB_DEVICE\\App>"
    "$<$<AND:$<CONFIG:Debug>,$<COMPILE_LANGUAGE:CXX>>:${PROJECT_SOURCE_DIR}/USB_DEVICE\\Target>"
    "$<$<AND:$<CONFIG:Debug>,$<COMPILE_LANGUAGE:CXX>>:${PROJECT_SOURCE_DIR}/Middlewares\\ST\\STM32_USB_Device_Library\\Core\\Inc>"
    "$<$<AND:$<CONFIG:Debug>,$<COMPILE_LANGUAGE:CXX>>:${PROJECT_SOURCE_DIR}/Middlewares\\ST\\STM32_USB_Device_Library\\Class\\CDC\\Inc>"
    "$<$<AND:$<NOT:$<CONFIG:Debug>>,$<COMPILE_LANGUAGE:C>>:${PROJECT_SOURCE_DIR}/Core\\Inc>"
    "$<$<AND:$<NOT:$<CONFIG:Debug>>,$<COMPILE_LANGUAGE:C>>:${PROJECT_SOURCE_DIR}/Drivers\\STM32F3xx_HAL_Driver\\Inc\\Legacy>"
    "$<$<AND:$<NOT:$<CONFIG:Debug>>,$<COMPILE_LANGUAGE:C>>:${PROJECT_SOURCE_DIR}/Drivers\\STM32F3xx_HAL_Driver\\Inc>"
    "$<$<AND:$<NOT:$<CONFIG:Debug>>,$<COMPILE_LANGUAGE:C>>:${PROJECT_SOURCE_DIR}/Drivers\\CMSIS\\Device\\ST\\STM32F3xx\\Include>"
    "$<$<AND:$<NOT:$<CONFIG:Debug>>,$<COMPILE_LANGUAGE:C>>:${PROJECT_SOURCE_DIR}/Drivers\\CMSIS\\Include>"
    "$<$<AND:$<NOT:$<CONFIG:Debug>>,$<COMPILE_LANGUAGE:C>>:${PROJECT_SOURCE_DIR}/USB_DEVICE\\App>"
    "$<$<AND:$<NOT:$<CONFIG:Debug>>,$<COMPILE_LANGUAGE:C>>:${PROJECT_SOURCE_DIR}/USB_DEVICE\\Target>"
    "$<$<AND:$<NOT:$<CONFIG:Debug>>,$<COMPILE_LANGUAGE:C>>:${PROJECT_SOURCE_DIR}/Middlewares\\ST\\STM32_USB_Device_Library\\Core\\Inc>"
    "$<$<AND:$<NOT:$<CONFIG:Debug>>,$<COMPILE_LANGUAGE:C>>:${PROJECT_SOURCE_DIR}/Middlewares\\ST\\STM32_USB_Device_Library\\Class\\CDC\\Inc>"
    "$<$<AND:$<NOT:$<CONFIG:Debug>>,$<COMPILE_LANGUAGE:C>>:${PROJECT_SOURCE_DIR}/FATFS\\Target>"
    "$<$<AND:$<NOT:$<CONFIG:Debug>>,$<COMPILE_LANGUAGE:C>>:${PROJECT_SOURCE_DIR}/FATFS\\App>"
    "$<$<AND:$<NOT:$<CONFIG:Debug>>,$<COMPILE_LANGUAGE:C>>:${PROJECT_SOURCE_DIR}/Middlewares\\Third_Party\\FatFs\\src>"
    "$<$<AND:$<NOT:$<CONFIG:Debug>>,$<COMPILE_LANGUAGE:CXX>>:${PROJECT_SOURCE_DIR}/Core\\Inc>"
    "$<$<AND:$<NOT:$<CONFIG:Debug>>,$<COMPILE_LANGUAGE:CXX>>:${PROJECT_SOURCE_DIR}/Drivers\\STM32F3xx_HAL_Driver\\Inc\\Legacy>"
    "$<$<AND:$<NOT:$<CONFIG:Debug>>,$<COMPILE_LANGUAGE:CXX>>:${PROJECT_SOURCE_DIR}/Drivers\\STM32F3xx_HAL_Driver\\Inc>"
    "$<$<AND:$<NOT:$<CONFIG:Debug>>,$<COMPILE_LANGUAGE:CXX>>:${PROJECT_SOURCE_DIR}/Drivers\\CMSIS\\Device\\ST\\STM32F3xx\\Include>"
    "$<$<AND:$<NOT:$<CONFIG:Debug>>,$<COMPILE_LANGUAGE:CXX>>:${PROJECT_SOURCE_DIR}/Drivers\\CMSIS\\Include>"
    "$<$<AND:$<NOT:$<CONFIG:Debug>>,$<COMPILE_LANGUAGE:CXX>>:${PROJECT_SOURCE_DIR}/USB_DEVICE\\App>"
    "$<$<AND:$<NOT:$<CONFIG:Debug>>,$<COMPILE_LANGUAGE:CXX>>:${PROJECT_SOURCE_DIR}/USB_DEVICE\\Target>"
    "$<$<AND:$<NOT:$<CONFIG:Debug>>,$<COMPILE_LANGUAGE:CXX>>:${PROJECT_SOURCE_DIR}/Middlewares\\ST\\STM32_USB_Device_Library\\Core\\Inc>"
    "$<$<AND:$<NOT:$<CONFIG:Debug>>,$<COMPILE_LANGUAGE:CXX>>:${PROJECT_SOURCE_DIR}/Middlewares\\ST\\STM32_USB_Device_Library\\Class\\CDC\\Inc>"
)

target_compile_options(
    ${TARGET_NAME} PRIVATE
    "$<$<AND:$<CONFIG:Debug>,$<COMPILE_LANGUAGE:ASM>>:-g3>"
    "$<$<AND:$<CONFIG:Debug>,$<COMPILE_LANGUAGE:C>>:-g3>"
    "$<$<AND:$<CONFIG:Debug>,$<COMPILE_LANGUAGE:CXX>>:-g3>"
    "$<$<AND:$<NOT:$<CONFIG:Debug>>,$<COMPILE_LANGUAGE:ASM>>:-g0>"
    "$<$<AND:$<NOT:$<CONFIG:Debug>>,$<COMPILE_LANGUAGE:C>>:-g0>"
    "$<$<AND:$<NOT:$<CONFIG:Debug>>,$<COMPILE_LANGUAGE:CXX>>:-g0>"
    "$<$<AND:$<CONFIG:Debug>,$<COMPILE_LANGUAGE:C>>:-Og>"
    "$<$<AND:$<NOT:$<CONFIG:Debug>>,$<COMPILE_LANGUAGE:C>>:-Os>"
    "$<$<AND:$<NOT:$<CONFIG:Debug>>,$<COMPILE_LANGUAGE:CXX>>:-Os>"
    "$<$<AND:$<CONFIG:Debug>,$<COMPILE_LANGUAGE:C>>:>"
    "$<$<AND:$<CONFIG:Debug>,$<COMPILE_LANGUAGE:CXX>>:>"
    "$<$<AND:$<NOT:$<CONFIG:Debug>>,$<COMPILE_LANGUAGE:C>>:>"
    "$<$<AND:$<NOT:$<CONFIG:Debug>>,$<COMPILE_LANGUAGE:CXX>>:>"
    "$<$<CONFIG:Debug>:-mcpu=cortex-m4>"
    "$<$<CONFIG:Debug>:-mfpu=fpv4-sp-d16>"
    "$<$<CONFIG:Debug>:-mfloat-abi=hard>"
    "$<$<NOT:$<CONFIG:Debug>>:-mcpu=cortex-m4>"
    "$<$<NOT:$<CONFIG:Debug>>:-mfpu=fpv4-sp-d16>"
    "$<$<NOT:$<CONFIG:Debug>>:-mfloat-abi=hard>"
)

target_link_libraries(
    ${TARGET_NAME} PRIVATE
)

target_link_directories(
    ${TARGET_NAME} PRIVATE
)

target_link_options(
    ${TARGET_NAME} PRIVATE
    "$<$<CONFIG:Debug>:-mcpu=cortex-m4>"
    "$<$<CONFIG:Debug>:-mfpu=fpv4-sp-d16>"
    "$<$<CONFIG:Debug>:-mfloat-abi=hard>"
    "$<$<NOT:$<CONFIG:Debug>>:-mcpu=cortex-m4>"
    "$<$<NOT:$<CONFIG:Debug>>:-mfpu=fpv4-sp-d16>"
    "$<$<NOT:$<CONFIG:Debug>>:-mfloat-abi=hard>"
    -T
    "$<$<CONFIG:Debug>:${PROJECT_SOURCE_DIR}/STM32F302CBTX_FLASH.ld>"
    "$<$<NOT:$<CONFIG:Debug>>:${PROJECT_SOURCE_DIR}/STM32F302CBTX_FLASH.ld>"
)

target_sources(
    ${TARGET_NAME} PRIVATE
    "Core\\Src\\logging.c"
    "Core\\Src\\lps22hb.c"
    "Core\\Src\\lsm6dso.c"
    "Core\\Src\\main.c"
    "Core\\Src\\radio.c"
    "Core\\Src\\stm32f3xx_hal_msp.c"
    "Core\\Src\\stm32f3xx_it.c"
    "Core\\Src\\syscalls.c"
    "Core\\Src\\sysmem.c"
    "Core\\Src\\system_stm32f3xx.c"
    "Core\\Src\\usb_descriptors.c"
    "Core\\Src\\utils.c"
    "Core\\Startup\\startup_stm32f302c8tx.s"
    "FATFS\\App\\fatfs.c"
    "FATFS\\Target\\user_diskio_spi.c"
    "FATFS\\Target\\user_diskio.c"
    "Middlewares\\Third_Party\\FatFs\\src\\diskio.c"
    "Middlewares\\Third_Party\\FatFs\\src\\ff_gen_drv.c"
    "Middlewares\\Third_Party\\FatFs\\src\\ff.c"
    "Middlewares\\Third_Party\\FatFs\\src\\option\\syscall.c"
    "Drivers\\lps22hb-pid\\lps22hb_reg.c"
    "Drivers\\lsm6dsox-pid\\lsm6dsox_reg.c"
    "Drivers\\STM32F3xx_HAL_Driver\\Src\\stm32f3xx_hal_adc_ex.c"
    "Drivers\\STM32F3xx_HAL_Driver\\Src\\stm32f3xx_hal_adc.c"
    "Drivers\\STM32F3xx_HAL_Driver\\Src\\stm32f3xx_hal_can.c"
    "Drivers\\STM32F3xx_HAL_Driver\\Src\\stm32f3xx_hal_cortex.c"
    "Drivers\\STM32F3xx_HAL_Driver\\Src\\stm32f3xx_hal_dma.c"
    "Drivers\\STM32F3xx_HAL_Driver\\Src\\stm32f3xx_hal_exti.c"
    "Drivers\\STM32F3xx_HAL_Driver\\Src\\stm32f3xx_hal_flash_ex.c"
    "Drivers\\STM32F3xx_HAL_Driver\\Src\\stm32f3xx_hal_flash.c"
    "Drivers\\STM32F3xx_HAL_Driver\\Src\\stm32f3xx_hal_gpio.c"
    "Drivers\\STM32F3xx_HAL_Driver\\Src\\stm32f3xx_hal_i2c_ex.c"
    "Drivers\\STM32F3xx_HAL_Driver\\Src\\stm32f3xx_hal_i2c.c"
    "Drivers\\STM32F3xx_HAL_Driver\\Src\\stm32f3xx_hal_pcd_ex.c"
    "Drivers\\STM32F3xx_HAL_Driver\\Src\\stm32f3xx_hal_pcd.c"
    "Drivers\\STM32F3xx_HAL_Driver\\Src\\stm32f3xx_hal_pwr_ex.c"
    "Drivers\\STM32F3xx_HAL_Driver\\Src\\stm32f3xx_hal_pwr.c"
    "Drivers\\STM32F3xx_HAL_Driver\\Src\\stm32f3xx_hal_rcc_ex.c"
    "Drivers\\STM32F3xx_HAL_Driver\\Src\\stm32f3xx_hal_rcc.c"
    "Drivers\\STM32F3xx_HAL_Driver\\Src\\stm32f3xx_hal_spi_ex.c"
    "Drivers\\STM32F3xx_HAL_Driver\\Src\\stm32f3xx_hal_spi.c"
    "Drivers\\STM32F3xx_HAL_Driver\\Src\\stm32f3xx_hal_tim_ex.c"
    "Drivers\\STM32F3xx_HAL_Driver\\Src\\stm32f3xx_hal_tim.c"
    "Drivers\\STM32F3xx_HAL_Driver\\Src\\stm32f3xx_hal_uart_ex.c"
    "Drivers\\STM32F3xx_HAL_Driver\\Src\\stm32f3xx_hal_uart.c"
    "Drivers\\STM32F3xx_HAL_Driver\\Src\\stm32f3xx_hal.c"
    "Drivers\\STM32F3xx_HAL_Driver\\Src\\stm32f3xx_ll_usb.c"
    "Drivers\\sx126x_driver\\src\\lr_fhss_mac.c"
    "Drivers\\sx126x_driver\\src\\sx126x_driver_version.c"
    "Drivers\\sx126x_driver\\src\\sx126x_lr_fhss.c"
    "Drivers\\sx126x_driver\\src\\sx126x.c"
    "Drivers\\tinyusb\\src\\class\\audio\\audio_device.c"
    "Drivers\\tinyusb\\src\\class\\bth\\bth_device.c"
    "Drivers\\tinyusb\\src\\class\\cdc\\cdc_device.c"
    "Drivers\\tinyusb\\src\\class\\cdc\\cdc_host.c"
    "Drivers\\tinyusb\\src\\class\\cdc\\cdc_rndis_host.c"
    "Drivers\\tinyusb\\src\\class\\dfu\\dfu_device.c"
    "Drivers\\tinyusb\\src\\class\\dfu\\dfu_rt_device.c"
    "Drivers\\tinyusb\\src\\class\\hid\\hid_device.c"
    "Drivers\\tinyusb\\src\\class\\hid\\hid_host.c"
    "Drivers\\tinyusb\\src\\class\\midi\\midi_device.c"
    "Drivers\\tinyusb\\src\\class\\msc\\msc_device.c"
    "Drivers\\tinyusb\\src\\class\\msc\\msc_host.c"
    "Drivers\\tinyusb\\src\\class\\net\\ecm_rndis_device.c"
    "Drivers\\tinyusb\\src\\class\\net\\ncm_device.c"
    "Drivers\\tinyusb\\src\\class\\usbtmc\\usbtmc_device.c"
    "Drivers\\tinyusb\\src\\class\\vendor\\vendor_device.c"
    "Drivers\\tinyusb\\src\\class\\vendor\\vendor_host.c"
    "Drivers\\tinyusb\\src\\class\\video\\video_device.c"
    "Drivers\\tinyusb\\src\\common\\tusb_fifo.c"
    "Drivers\\tinyusb\\src\\device\\usbd_control.c"
    "Drivers\\tinyusb\\src\\device\\usbd.c"
    "Drivers\\tinyusb\\src\\host\\hub.c"
    "Drivers\\tinyusb\\src\\host\\usbh.c"
    "Drivers\\tinyusb\\src\\portable\\analog\\max3421\\hcd_max3421.c"
    "Drivers\\tinyusb\\src\\portable\\bridgetek\\ft9xx\\dcd_ft9xx.c"
    "Drivers\\tinyusb\\src\\portable\\chipidea\\ci_fs\\dcd_ci_fs.c"
    "Drivers\\tinyusb\\src\\portable\\chipidea\\ci_hs\\dcd_ci_hs.c"
    "Drivers\\tinyusb\\src\\portable\\chipidea\\ci_hs\\hcd_ci_hs.c"
    "Drivers\\tinyusb\\src\\portable\\dialog\\da146xx\\dcd_da146xx.c"
    "Drivers\\tinyusb\\src\\portable\\ehci\\ehci.c"
    "Drivers\\tinyusb\\src\\portable\\espressif\\esp32sx\\dcd_esp32sx.c"
    "Drivers\\tinyusb\\src\\portable\\mentor\\musb\\dcd_musb.c"
    "Drivers\\tinyusb\\src\\portable\\mentor\\musb\\hcd_musb.c"
    "Drivers\\tinyusb\\src\\portable\\microchip\\pic\\dcd_pic.c"
    "Drivers\\tinyusb\\src\\portable\\microchip\\pic32mz\\dcd_pic32mz.c"
    "Drivers\\tinyusb\\src\\portable\\microchip\\samd\\dcd_samd.c"
    "Drivers\\tinyusb\\src\\portable\\microchip\\samg\\dcd_samg.c"
    "Drivers\\tinyusb\\src\\portable\\microchip\\samx7x\\dcd_samx7x.c"
    "Drivers\\tinyusb\\src\\portable\\mindmotion\\mm32\\dcd_mm32f327x_otg.c"
    "Drivers\\tinyusb\\src\\portable\\nordic\\nrf5x\\dcd_nrf5x.c"
    "Drivers\\tinyusb\\src\\portable\\nuvoton\\nuc120\\dcd_nuc120.c"
    "Drivers\\tinyusb\\src\\portable\\nuvoton\\nuc121\\dcd_nuc121.c"
    "Drivers\\tinyusb\\src\\portable\\nuvoton\\nuc505\\dcd_nuc505.c"
    "Drivers\\tinyusb\\src\\portable\\nxp\\khci\\dcd_khci.c"
    "Drivers\\tinyusb\\src\\portable\\nxp\\khci\\hcd_khci.c"
    "Drivers\\tinyusb\\src\\portable\\nxp\\lpc_ip3511\\dcd_lpc_ip3511.c"
    "Drivers\\tinyusb\\src\\portable\\nxp\\lpc17_40\\dcd_lpc17_40.c"
    "Drivers\\tinyusb\\src\\portable\\nxp\\lpc17_40\\hcd_lpc17_40.c"
    "Drivers\\tinyusb\\src\\portable\\ohci\\ohci.c"
    "Drivers\\tinyusb\\src\\portable\\raspberrypi\\pio_usb\\dcd_pio_usb.c"
    "Drivers\\tinyusb\\src\\portable\\raspberrypi\\pio_usb\\hcd_pio_usb.c"
    "Drivers\\tinyusb\\src\\portable\\raspberrypi\\rp2040\\dcd_rp2040.c"
    "Drivers\\tinyusb\\src\\portable\\raspberrypi\\rp2040\\hcd_rp2040.c"
    "Drivers\\tinyusb\\src\\portable\\raspberrypi\\rp2040\\rp2040_usb.c"
    "Drivers\\tinyusb\\src\\portable\\renesas\\rusb2\\dcd_rusb2.c"
    "Drivers\\tinyusb\\src\\portable\\renesas\\rusb2\\hcd_rusb2.c"
    "Drivers\\tinyusb\\src\\portable\\renesas\\rusb2\\rusb2_common.c"
    "Drivers\\tinyusb\\src\\portable\\sony\\cxd56\\dcd_cxd56.c"
    "Drivers\\tinyusb\\src\\portable\\st\\stm32_fsdev\\dcd_stm32_fsdev.c"
    "Drivers\\tinyusb\\src\\portable\\st\\typec\\typec_stm32.c"
    "Drivers\\tinyusb\\src\\portable\\sunxi\\dcd_sunxi_musb.c"
    "Drivers\\tinyusb\\src\\portable\\synopsys\\dwc2\\dcd_dwc2.c"
    "Drivers\\tinyusb\\src\\portable\\template\\dcd_template.c"
    "Drivers\\tinyusb\\src\\portable\\template\\hcd_template.c"
    "Drivers\\tinyusb\\src\\portable\\ti\\msp430x5xx\\dcd_msp430x5xx.c"
    "Drivers\\tinyusb\\src\\portable\\valentyusb\\eptri\\dcd_eptri.c"
    "Drivers\\tinyusb\\src\\portable\\wch\\dcd_ch32_usbhs.c"
    "Drivers\\tinyusb\\src\\tusb.c"
    "Drivers\\tinyusb\\src\\typec\\usbc.c"
    "Drivers\\ubx_parser\\neo_m8_conversion.c"
    "Drivers\\ubx_parser\\neo_m8_gps.c"
    "Drivers\\ubx_parser\\neo_m8_ubx_checksum.c"
    "Drivers\\ubx_parser\\ringbuffer_char.c"
)

add_custom_command(
    TARGET ${TARGET_NAME} POST_BUILD
    COMMAND ${CMAKE_SIZE} $<TARGET_FILE:${TARGET_NAME}>
)

add_custom_command(
    TARGET ${TARGET_NAME} POST_BUILD
    COMMAND ${CMAKE_OBJCOPY} -O ihex
    $<TARGET_FILE:${TARGET_NAME}> ${TARGET_NAME}.hex
)

add_custom_command(
    TARGET ${TARGET_NAME} POST_BUILD
    COMMAND ${CMAKE_OBJCOPY} -O binary
    $<TARGET_FILE:${TARGET_NAME}> ${TARGET_NAME}.bin
)

endfunction()